version: '3.7'

services:
  postgres:
    restart: always
    hostname: online-shop
    image: postgres:latest
    volumes:
      - ./datagrip/dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=pgpass
    ports:
      - 5432:5432