version: '3.7'

services:
  server:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      - WAIT_HOSTS=postgres:6000
      - WAIT_HOSTS=redis:6379
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - PORT=8080
      - DBFLAG=true
  image-service:
    build: ./image-service
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      - PORT=8081
      - DBFLAG=true
  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./datagrip/dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=pgpass
    ports:
      - 6000:5432
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  frontend:
    build: ./frontend
    hostname: frontend
    tty: true
    environment:
      - WAIT_HOSTS=server:8080
      - WAIT_HOSTS=image-service:8081
      - SERVER_HOST=server
      - IMAGE_HOST=image-service
    ports:
      - 80:80

volumes:
  redis-data:
  redis-conf: