version: '3.7'

services:
  server:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres
      - PORT=8080
      - DBFLAG=true
  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./datagrip/dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=pgpass
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    hostname: frontend
    tty: true
    ports:
      - 80:80